[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --verbose --html=reports/report.html --self-contained-html
markers =
    login: Login test scenarios
    search: Product search test scenarios
